apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: grpc-debug
  namespace: debug
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - grpc.testing.streamlayer.io
    port:
      number: 31400
      name: grpc
      protocol: http
  - hosts:
    - grpc.testing.streamlayer.io
    port:
      number: 443
      name: grpc-tls
      protocol: https
    tls:
      mode: SIMPLE
      serverCertificate: /etc/istio/ingressgateway-certs/grpc.testing.streamlayer.io.crt
      privateKey: /etc/istio/ingressgateway-certs/grpc.testing.streamlayer.io.key
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grpc
  namespace: debug
spec:
  gateways:
  - grpc-debug
  hosts:
  - grpc.testing.streamlayer.io
  http:
  - match:
    - port: 31400
    route:
    - destination:
        host: grpc-debug
        port:
          number: 50051
  - match:
    - port: 443
    route:
    - destination:
        host: grpc-debug
        port:
          number: 50051
